/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ATKzcoDsjsH
 */
import Link from "next/link"
import Image from "next/image"

export function Article2() {
  return (
    <section className="w-full">
      <header className="bg-white text-zinc-900 py-4 border-b">
        <div className="container mx-auto px-4 md:px-6">
          <nav className="flex items-center justify-between">
            <div className="text-2xl font-bold">Conspiracy Confirmed?</div>
            <div className="space-x-4">
              <Link className="text-zinc-900 hover:text-zinc-700" href="/">
                Home
              </Link>
            </div>
          </nav>
        </div>
      </header>
      <main className="container mx-auto px-4 md:px-6 py-8">
        <section className="mb-8">
          <h2 className="text-4xl font-bold mb-4">Conspiracy Confirmed?</h2>

          <p className="text-3xl dark:text-zinc-400 mb-4">
          Article: Unveiling the Truth Behind Lunar Landing Hoax
          </p>

          <p className="text-2xl dark:text-black-600 mb-4">
          For decades, humanity has marveled at the remarkable achievement of the Apollo missions, particularly the historic moment when Neil Armstrong set foot on the lunar surface in 1969. However, beneath the veneer of this celebrated accomplishment lies a conspiracy that challenges the very foundation of our understanding of space exploration. Here, we unveil the truth behind the alleged hoax of the lunar landings.          </p>
          
          <p className="text-3xl dark:text-zinc-400 mb-4">
          <video width="1280" height="720" controls preload="none">
            <source src="output.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>          
          </p>

          <p className="text-3xl dark:text-zinc-400 mb-4">
          Claim 1: The Footage Was Fabricated
          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
          One of the most compelling arguments propagated by skeptics is that the footage of the lunar landings was staged on Earth. They argue that the lack of stars in the sky, inconsistencies in shadows, and the fluttering flag all point to a meticulously crafted set on Earth rather than the desolate lunar landscape.          </p>
          
          <p className="text-2xl dark:text-black-400 mb-4">
          Proof: While these claims may appear convincing at first glance, they fail to withstand scrutiny under scientific analysis. The absence of stars in the lunar sky can be attributed to the camera settings and the bright lunar surface, which overwhelmed the faint starlight. Moreover, the peculiar shadows can be explained by the uneven terrain and the angle of the Sun, as demonstrated by experts in photogrammetry and lunar geology.          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
            <Image src={"https://gdb.voanews.com/01E5AEBB-03B1-4AC8-8A8B-CA753142CC3D_w408_r1_s.jpg"} alt={""} width={564} height={423} />
          </p>

          <p className="text-3xl dark:text-zinc-400 mb-4">
          Claim 2: Radiation Would Have Been Lethal
          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
          Conspiracy theorists often argue that the lethal radiation in space would have made the lunar missions impossible. They contend that astronauts would have been exposed to deadly doses of radiation from solar flares and cosmic rays, leading to their certain demise.          </p>
          
          <p className="text-2xl dark:text-black-400 mb-4">
          Proof: While space radiation is indeed a formidable challenge for long-duration space travel, the Apollo missions navigated this hazard by careful mission planning and shielding. The spacecraft were designed with protective layers to mitigate radiation exposure, and astronauts traveled through the Van Allen belts, the regions of intense radiation surrounding Earth, quickly enough to minimize risk. Furthermore, extensive studies conducted by NASA and independent researchers have concluded that the radiation doses received during the missions were within safe limits for the duration of the journey.
          </p>


          <p className="text-2xl dark:text-black-400 mb-4">
            <Image src={"https://cdn.mos.cms.futurecdn.net/c2YqcNpfcMUFFnNjUcanwD.jpg"} alt={""} width={564} height={423} />
          </p>


          <p className="text-3xl dark:text-zinc-400 mb-4">
          Claim 3: The Cold War Motive
          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
          A prevailing theory among conspiracy theorists is that the United States staged the lunar landings as a Cold War propaganda stunt to assert its technological superiority over the Soviet Union. They argue that the pressure to win the space race and the prestige associated with being the first nation to land on the Moon provided ample motivation for perpetrating the hoax.          </p>
          
          <p className="text-2xl dark:text-black-400 mb-4">
          Proof: While the geopolitical context of the Cold War undoubtedly influenced the space race, the notion that the United States would risk its credibility and reputation on a fraudulent moon landing is unfounded. The Apollo missions involved thousands of scientists, engineers, and technicians whose expertise and integrity would have been compromised by such a conspiracy. Moreover, the scientific data and samples returned from the Moon have been extensively studied and corroborated by researchers worldwide, reinforcing the authenticity of the lunar landings.          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
            <Image src={"https://smartcdn.gprod.postmedia.digital/nationalpost/wp-content/uploads/2019/07/afp_1iu32g.jpg?quality=90&strip=all&w=564&h=423&type=webp&sig=7VrnviYjeEqgLpAOisYp7Q"} alt={""} width={564} height={423} />
          </p>
          
          <p className="text-3xl dark:text-zinc-400 mb-4">
          Conclusion:
          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
          In conclusion, while conspiracy theories surrounding the lunar landings may persist, a critical examination of the evidence reveals a compelling narrative of human ingenuity, perseverance, and achievement in the face of adversity. Rather than succumbing to baseless speculation, let us celebrate the remarkable accomplishments of the Apollo missions and continue to explore the boundless frontier of space with curiosity and resolve.          </p>
          
          <p className="text-3xl dark:text-zinc-400 mb-4">
          Resources:
          </p>

          <p className="text-2xl dark:text-black-400 mb-4">
          The Cold War Led to the Moon Landing, but Historians Disagree on How <Link href={"https://nationalpost.com/news/the-cold-war-led-to-the-moon-landing-but-historians-disagree-on-how-the-moon-landing-influenced-the-war"}> https://nationalpost.com/news/the-cold-war-led-to-the-moon-landing-but-historians-disagree-on-how-the-moon-landing-influenced-the-war</Link> . Accessed 1 Feb. 2024.
          </p>
          <p className="text-2xl dark:text-black-400 mb-4">
          “Moon Landing Conspiracy Theories, Debunked.” Royal Museums Greenwich, <Link href={"https://www.rmg.co.uk/stories/topics/moon-landing-conspiracy-theories-debunked"}> www.rmg.co.uk/stories/topics/moon-landing-conspiracy-theories-debunked</Link> . Accessed 1 Feb. 2024.
          </p>
          <p className="text-2xl dark:text-black-400 mb-4">
          “Cosmic Radiation.” EPA, Environmental Protection Agency, <Link href={"www.epa.gov/radtown/cosmic-radiation"}> www.epa.gov/radtown/cosmic-radiation</Link> . Accessed 1 Feb. 2024.
          </p>


        </section>
      </main>
    </section>
  )
}
